spring.application.name=cashCare

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=cashCareSuperSecretKeyForJwtSigningMustBeAtLeast256BitsLong!!
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=604800000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=uploads
app.upload.max-size-bytes=10485760

openrouter.api-key = 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
openrouter.api-model = google/gemini-2.0-flash-001
openrouter.timeout-connect-ms = 10000
openrouter.timeout-read-ms = 60000
data.redis.host=localhost
data.redis.port=6379

